### ISSUE TITLE
Clarification  Please -- Images not showing up in my Imgur

### ISSUE THREAD

**Issue by aggied** [barisusakli/nodebb-plugin-imgur#10]
I might be doing this wrong (and I admit I'm new to Imgur as well), but does this plugin put images in my album for later download? Or does it just load them to Imgur anonymously? I'm assuming the latter, but would like some clarification. And if it is the latter, is the clientId just for rate limiting then?

**Comment by barisusakli** [comment]
Yes it uploads anonymously and imgur requires a client ID even for anon uploading.

**Comment by henrywright** [comment]
@barisusakli Is there a way to have the images my NodeBB users upload appear in an album on my Imgur? I'd like to be able to easily see what everyone has uploaded.

**Comment by barisusakli** [comment]
Published 1.0.0, you can upload to albums.

**Comment by henrywright** [comment]
Great @barisusakli thanks for the update, I'd like to upgrade to 1.0.0 but under my installed plugins it's saying 0.1.4 is the latest version?

**Comment by barisusakli** [comment]
There seems to be an issue with our package manager, in the mean time you can install it with npm i nodebb-plugin-imgur@1.0.0
