### ISSUE TITLE
Bulk upload not working correctly on mobile

### ISSUE THREAD

**Issue by martyalicante** [barisusakli/nodebb-plugin-imgur#18]
here is some bugs been detected on mobiles, on desktop works perfect
- uploading more than 1 photo at same time doesnt work, usually you get the same link x2,x3 etc
- uploading 1 photo and save post, next edit post and try upload another photo and it will rewrite previous link so you get new link x 2

happens to me on safari IOS

**Comment by barisusakli** [comment]
Please report these on the composer plugins, this plugin doesn't deal with the front end stuff. It just uploads the image to imgur and return back an url.
