### ISSUE TITLE
iOS mobile multiple image upload results in overwrite of other images

### ISSUE THREAD

**Issue by anthony-njctl** [barisusakli/nodebb-plugin-imgur#20]
If I post two images through my phone in a single post, the second image will cause the first image's markup to be rewritten the same as the second image.  The progress indicator will be duplicated, and the resulting image will be duplicated.

**Comment by anthony-njctl** [comment]
I'm not sure if this is a bug in the imgur plugin or if it's a bug in nodeBB core -- I can submit a bug over there if needed.

**Comment by barisusakli** [comment]
https://github.com/barisusakli/nodebb-plugin-imgur/issues/18
