### ISSUE TITLE
invalid-refresh-token

### ISSUE THREAD

**Issue by leoGalani** [barisusakli/nodebb-plugin-imgur#21]
Hi,

Just got last version and im getting this error.

invalid-refresh-token

Here is what happens on my log

20/10 21:58 [23492] - error: [plugins] filter:uploadImage,  invalid-refresh-token

**Comment by barisusakli** [comment]
Did you set up a imgur app with oath and entered the key? After that click authorize.

**Comment by felirami** [comment]
I'm having the exact same error

**Comment by kacemlight** [comment]
I have the same issue!!

**Comment by barisusakli** [comment]
What happens when you guys click `Authorize` in the ACP page for the plugin?

**Comment by felirami** [comment]
I go to the page of imgur and authorize the app, no error there. After everything, the app tells that error

**Comment by An-Lin** [comment]
I am experiencing this issue as well. Hopefully it get fix soon!

**Comment by sunsetbrew** [comment]
I am seeing this as well

**Comment by barisusakli** [comment]
Are you guys clicking save after you put in the key/secret?

**Comment by sunsetbrew** [comment]
I figured out what it was.  It was user error because I was not entering the return url in imgur.  I need to read better.  Sorry.
