### ISSUE TITLE
no-imgur-client-id

### ISSUE THREAD

**Issue by kdpuvvadi** [barisusakli/nodebb-plugin-imgur#25]
i'm getting this error after authorizing and allowing api.
Internal error.
Oops! Looks like something went wrong!
/admin/plugins/imgur/oauth
no-imgur-client-id

**Comment by Roman2204** [comment]
I've got this error too:
```
    Внутренняя ошибка.
    Упс! Похоже, что-то пошло не так!
    /admin/plugins/imgur/oauth
    no-imgur-client-id
```
Does anyone know how to solve this?

**Comment by barisusakli** [comment]
Are you guys clicking `Save` after putting in the key/secret? You should click `Save` then `Authorize`.

**Comment by kdpuvvadi** [comment]
Saved it before authorizing it but still
