### ISSUE TITLE
Can't open plugin settings at all (v1.5.1)

### ISSUE THREAD

**Issue by aliasfalse** [barisusakli/nodebb-plugin-imgur#32]

**Comment by barisusakli** [comment]
Works fine for me, please post the version of the plugin you are using and your nodebb git hash.

**Comment by aliasfalse** [comment]
Plugin: 1.0.18
Nodebb: No idea on the hash, I just upgraded to v1.5.1, which is currently [e641047](https://github.com/NodeBB/NodeBB/commit/e64104786ffdd8471119dc54660c3fc12f3202a1)

**Comment by barisusakli** [comment]
Do you see any error messages in the browser or server console?

**Comment by aliasfalse** [comment]
Yes, ajaxify errors.
```bash
ajaxify.js:331 Uncaught Error: Unable to load template: admin/plugins/imgur (error)
    at Object.error (ajaxify.js:331)
    at l (jquery.js:3305)
    at Object.fireWith [as rejectWith] (jquery.js:3435)
    at C (jquery.js:9244)
    at XMLHttpRequest.<anonymous> (jquery.js:9484)
```

**Comment by barisusakli** [comment]
Did you run `./nodebb build` before starting nodebb?

**Comment by aliasfalse** [comment]
yes, the rest of the site works fine.

**Comment by aliasfalse** [comment]
i just did another build after uninstalling and reinstalling the plugin and it lets me onto the page now.

**Comment by aliasfalse** [comment]
still probably need to add to some sort of readme or debug steps, cause I added other plugins after the first build i did that worked fine.
