### ISSUE TITLE
update to latest api

### ISSUE THREAD

**Issue by exomarty** [barisusakli/nodebb-plugin-imgur#34]
imgur now uses v3 api
https://apidocs.imgur.com/#authorization-and-oauth

I´m not able to authorize the app anymore

{"data":{"error":"Unauthorized","request":"\/oauth2\/authorize","method":"POST"},"success":false,"status":403}

**Comment by barisusakli** [comment]
Not sure what's wrong, tried to update it based on those docs, but I am still getting the same error. Maybe someone else who knows imgurs oauth system can send in a PR

**Comment by barisusakli** [comment]
Looks like imgur is having problems, 

http://status.imgur.com/
```
Aug 30, 2018

Scheduled Maintenance
Resolved - This incident has been resolved. 
Aug 30, 04:16 PDT
Monitoring - Multiple fixes have been made to improve site stability, we will continue to monitor these fixes and resolve any further issues that crop up.

Third party logins are unfortunately still not working at this time. 
```

Third party logins are not working so if you were trying to auth via facebook,google or twitter etc. it would give that error.

I will take a look again once they fix their problems.

**Comment by exomarty** [comment]
Yes. It seems they have major problems. 
I tried with new account without 3rd party but the page to create and api key doesnt works. It just open image gallery.

**Comment by barisusakli** [comment]
Yes I wasn't able to create new apps either.

**Comment by exomarty** [comment]
imgur app creation is restored and i was able to get access token with postman test app
however authorization on this plugin is still not working
i think it should use &response_type=token instead of &response_type=code and then save ( refresh access etc ) values correctly

**Comment by exomarty** [comment]
i got the tokens manually and wrote them on mongo imgur-plugin key but still not working

**Comment by barisusakli** [comment]
If you manually change the keys in mongodb, you need to restart nodebb because the data is cached.

Either way I will update this plugin to use the latest API, seems like the way to get the tokens changed and it has to be done client side now.

**Comment by barisusakli** [comment]
let me know if 1.1.0 works

**Comment by barisusakli** [comment]
Change your callback url in the imgur app to `/admin/plugins/imgur`

**Comment by exomarty** [comment]
setting that callback sends me back to the plugin admin page ( i can see the url admin/plugins/imgur/?code=thecode) but doesnt seems to enable he authorization at all

my setup
![screenshot_22](https://user-images.githubusercontent.com/10746278/45179252-4a481f80-b218-11e8-9f57-c9cfb667feb0.png)

**Comment by exomarty** [comment]
access token and  refresh token remain unchaged at the mongo db

**Comment by barisusakli** [comment]
Can you check your browser network tab for the POST request to /admin/plugins/imgur/tokens, 
let me know if it is sending the new tokens to the server side.

**Comment by exomarty** [comment]
not a big expert on newtwork tab
i only see this

![screenshot_23](https://user-images.githubusercontent.com/10746278/45180794-ce040b00-b21c-11e8-88ae-09ff81192fc3.png)

and the final url

![screenshot_24](https://user-images.githubusercontent.com/10746278/45180805-d5c3af80-b21c-11e8-9137-db7ecb31d78c.png)

**Comment by barisusakli** [comment]
Are you sure you have the latest version? Your url still uses response_type=code it should be response_type=token in the latest version.

**Comment by exomarty** [comment]
Should be
I just cloned it from github

**Comment by exomarty** [comment]
Working ok. It was a problem with npm connection on my server
