### ISSUE TITLE
Imgur is temporarily over capacity. Please try again later

### ISSUE THREAD

**Issue by MaxWaldorf** [barisusakli/nodebb-plugin-imgur#39]
Since a couple days, the plugin push this error constantly...

Is there a way to see if this is a true imgur issue or something changed in the API that needs fixing?

Using latest version on a v2.8.12 installation

**Comment by barisusakli** [comment]
Lots of reports of this on the web, I don't think anything changed in the api for making a image upload https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139
